---
apiVersion: v2
type: application
appVersion: "0.0.1"
version: 0.1.0
name: tailscale-ingress-controller
description: A wrapper around the nginx ingress controller, allowing it to join tailscale networks
sources:
  - https://github.com/pthomison/tailscale-ingress-controller

dependencies:
- name: ingress-nginx
  version: "~4"
  repository: "https://kubernetes.github.io/ingress-nginx"
  
maintainers:
  - name: Patrick Thomison
    email: tbd@tbd.com